-- MySQL Script generated by MySQL Workbench
-- 05/21/16 15:16:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`People`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`People` (
  `person_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Worker` (
  `worker_num` INT NOT NULL DEFAULT userID,
  `person_id` VARCHAR(9) NOT NULL,
  `password` VARCHAR(15) NULL,
  `is_connected` TINYINT(1) NULL,
  `clinic_num` INT NULL,
  `worker_type` VARCHAR(15) NULL,
  PRIMARY KEY (`worker_num`),
  INDEX `fk_Medical_Worker_People1_idx` (`person_id` ASC),
  CONSTRAINT `fk_Medical_Worker_People1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`People` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calendar` (
  `calendar_num` INT NOT NULL,
  `date` DATE NOT NULL,
  `h8` TINYINT(1) NULL,
  `h9` TINYINT(1) NULL,
  `h10` TINYINT(1) NULL,
  `h11` TINYINT(1) NULL,
  `h12` TINYINT(1) NULL,
  `h13` TINYINT(1) NULL,
  `h14` TINYINT(1) NULL,
  `h15` TINYINT(1) NULL,
  `h16` TINYINT(1) NULL,
  `h17` TINYINT(1) NULL,
  `h18` TINYINT(1) NULL,
  `h19` TINYINT(1) NULL,
  PRIMARY KEY (`calendar_num`, `date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Worker_in_Clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Worker_in_Clinic` (
  `clinic_num` INT NOT NULL,
  `worker_num` INT NOT NULL,
  `calendar_num` INT NOT NULL,
  PRIMARY KEY (`clinic_num`, `worker_num`),
  INDEX `fk_Medical_Worker_in_Clinic_Medical_Worker1_idx` (`worker_num` ASC),
  INDEX `fk_Medical_Worker_in_Clinic_Calendar2_idx` (`calendar_num` ASC),
  CONSTRAINT `fk_Medical_Worker_in_Clinic_Medical_Worker1`
    FOREIGN KEY (`worker_num`)
    REFERENCES `mydb`.`Medical_Worker` (`worker_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Worker_in_Clinic_Calendar2`
    FOREIGN KEY (`calendar_num`)
    REFERENCES `mydb`.`Calendar` (`calendar_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `appointment_num` INT NOT NULL,
  `Medical_Worker_worker_num` INT NOT NULL,
  `clinic_num` INT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'arrived, didn\'t, open',
  `app_date` DATE NULL,
  `call_date` DATE NULL,
  `results` VARCHAR(45) NULL,
  PRIMARY KEY (`appointment_num`),
  INDEX `fk_Appointments_Medical_Worker1_idx` (`Medical_Worker_worker_num` ASC),
  CONSTRAINT `fk_Appointments_Medical_Worker1`
    FOREIGN KEY (`Medical_Worker_worker_num`)
    REFERENCES `mydb`.`Medical_Worker` (`worker_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Expertise` (
  `expertise_code` INT NOT NULL,
  `expertise_name` VARCHAR(45) NULL,
  PRIMARY KEY (`expertise_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experts` (
  `worker_num` INT NOT NULL,
  `expertise_code` INT NOT NULL,
  PRIMARY KEY (`worker_num`),
  INDEX `fk_Experts_Medical_Worker1_idx` (`worker_num` ASC),
  INDEX `fk_Experts_Expertise1_idx` (`expertise_code` ASC),
  CONSTRAINT `fk_Experts_Medical_Worker1`
    FOREIGN KEY (`worker_num`)
    REFERENCES `mydb`.`Medical_Worker` (`worker_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experts_Expertise1`
    FOREIGN KEY (`expertise_code`)
    REFERENCES `mydb`.`Expertise` (`expertise_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Referrals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Referrals` (
  `referral_num` INT NOT NULL,
  `expertise_code` INT NOT NULL,
  `clinic_num` INT NULL,
  `referring_doctor_name` VARCHAR(45) NULL,
  `referring_doctor_email` VARCHAR(45) NULL,
  `urgency` INT NULL DEFAULT 1 (low) - 5 (high),
  `reason` VARCHAR(45) NULL,
  PRIMARY KEY (`referral_num`),
  INDEX `fk_Referrals_Expertise1_idx` (`expertise_code` ASC),
  CONSTRAINT `fk_Referrals_Expertise1`
    FOREIGN KEY (`expertise_code`)
    REFERENCES `mydb`.`Expertise` (`expertise_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`References_Files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`References_Files` (
  `references_file_num` INT NOT NULL,
  `referral_num` INT NOT NULL,
  PRIMARY KEY (`references_file_num`, `referral_num`),
  INDEX `fk_References_Files_Referrals1_idx` (`referral_num` ASC),
  CONSTRAINT `fk_References_Files_Referrals1`
    FOREIGN KEY (`referral_num`)
    REFERENCES `mydb`.`Referrals` (`referral_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report_File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report_File` (
  `report_file_num` INT NOT NULL,
  `report_num` INT NOT NULL,
  `expertise_code` INT NULL,
  `description` VARCHAR(45) NULL,
  `internal\extrnal` TINYINT(1) NULL DEFAULT internal = 0, extrnal = 1,
  PRIMARY KEY (`report_file_num`, `report_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment_file` (
  `appointment_file_num` INT NOT NULL,
  `appointment_num` INT NOT NULL,
  PRIMARY KEY (`appointment_file_num`, `appointment_num`),
  INDEX `fk_Appointment_file_Appointments1_idx` (`appointment_num` ASC),
  CONSTRAINT `fk_Appointment_file_Appointments1`
    FOREIGN KEY (`appointment_num`)
    REFERENCES `mydb`.`Appointments` (`appointment_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lab_Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lab_Tests` (
  `lab_test_num` INT NOT NULL,
  `appointment_num` INT NOT NULL,
  `lab_test_type` VARCHAR(45) NULL,
  `notes` VARCHAR(45) NULL,
  `results` VARCHAR(45) NULL,
  `pictures` VARCHAR(45) NULL DEFAULT 'pdf',
  PRIMARY KEY (`lab_test_num`),
  INDEX `fk_Lab_Tests_Appointments1_idx` (`appointment_num` ASC),
  CONSTRAINT `fk_Lab_Tests_Appointments1`
    FOREIGN KEY (`appointment_num`)
    REFERENCES `mydb`.`Appointments` (`appointment_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lab_Tests_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lab_Tests_file` (
  `lab_test_file_num` INT NOT NULL,
  `lab_test_num` INT NOT NULL,
  PRIMARY KEY (`lab_test_num`, `lab_test_file_num`),
  INDEX `fk_Lab_Tests_file_Lab_Tests1_idx` (`lab_test_num` ASC),
  CONSTRAINT `fk_Lab_Tests_file_Lab_Tests1`
    FOREIGN KEY (`lab_test_num`)
    REFERENCES `mydb`.`Lab_Tests` (`lab_test_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_Files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_Files` (
  `medical_file_num` INT NOT NULL,
  `references_file_num` INT NOT NULL,
  `appointment_file_num` INT NOT NULL,
  `report_file_num` INT NOT NULL,
  `lab_test_file_num` INT NOT NULL,
  PRIMARY KEY (`medical_file_num`),
  INDEX `fk_Medical_Files_References_Files1_idx` (`references_file_num` ASC),
  INDEX `fk_Medical_Files_Appointment_file1_idx` (`appointment_file_num` ASC),
  INDEX `fk_Medical_Files_Report_File1_idx` (`report_file_num` ASC),
  INDEX `fk_Medical_Files_Lab_Tests_file1_idx` (`lab_test_file_num` ASC),
  CONSTRAINT `fk_Medical_Files_References_Files1`
    FOREIGN KEY (`references_file_num`)
    REFERENCES `mydb`.`References_Files` (`references_file_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Files_Appointment_file1`
    FOREIGN KEY (`appointment_file_num`)
    REFERENCES `mydb`.`Appointment_file` (`appointment_file_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Files_Report_File1`
    FOREIGN KEY (`report_file_num`)
    REFERENCES `mydb`.`Report_File` (`report_file_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medical_Files_Lab_Tests_file1`
    FOREIGN KEY (`lab_test_file_num`)
    REFERENCES `mydb`.`Lab_Tests_file` (`lab_test_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurances` (
  `insurance_level` INT NOT NULL,
  `insurance_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`insurance_level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `patient_num` INT NOT NULL,
  `person_id` VARCHAR(9) NOT NULL,
  `medical_file_num` INT NOT NULL,
  `insurance_level` INT NOT NULL,
  `insurance_validity` TINYINT(1) NULL,
  `extensive_clinic_email` VARCHAR(45) NULL,
  `leave_date` DATE NULL,
  PRIMARY KEY (`patient_num`),
  INDEX `fk_Patients_People1_idx` (`person_id` ASC),
  INDEX `fk_Patients_Medical_Files1_idx` (`medical_file_num` ASC),
  INDEX `fk_Patients_Insurances1_idx` (`insurance_level` ASC),
  CONSTRAINT `fk_Patients_People1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`People` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_Medical_Files1`
    FOREIGN KEY (`medical_file_num`)
    REFERENCES `mydb`.`Medical_Files` (`medical_file_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patients_Insurances1`
    FOREIGN KEY (`insurance_level`)
    REFERENCES `mydb`.`Insurances` (`insurance_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Insurance_by_Expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Insurance_by_Expertise` (
  `expertise_code` INT NOT NULL,
  `insurance_level` INT NOT NULL,
  `insurance_name` VARCHAR(45) NULL,
  PRIMARY KEY (`expertise_code`, `insurance_level`),
  INDEX `fk_Insurance_by_Expertise_Expertise1_idx` (`expertise_code` ASC),
  INDEX `fk_Insurance_by_Expertise_Insurances1_idx` (`insurance_level` ASC),
  CONSTRAINT `fk_Insurance_by_Expertise_Expertise1`
    FOREIGN KEY (`expertise_code`)
    REFERENCES `mydb`.`Expertise` (`expertise_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insurance_by_Expertise_Insurances1`
    FOREIGN KEY (`insurance_level`)
    REFERENCES `mydb`.`Insurances` (`insurance_level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
