package common;
/**
 * 
 * This enum represents a client/server task. Based on this value the the client/server launch different methods.
 *
 */

public enum Operations {
	ANS,LOGIN,LOGOUT,TEST,ERROR,ALLOW_LOG,USER_ALREADY_LOGGED,GET_UT, GET_CUSTOMER, GET_CUSTOMER_ALL,
	UPDATE_CUSTOMER, GET_USER, GET_USER_ALL, UPDATE_USER, GET_USER_TYPE, GET_USER_TYPE_ALL, UPDATE_USER_TYPE,
	GET_PAYMENT_INFO, GET_PAYMENT_INFO_ALL, UPDATE_PAYMENT_INFO, CREATE_PAYMENT_INFO , GET_INVOICE, GET_INVOICE_ALL, 
	UPDATE_INVOICE, CREATE_INVOICE , GET_PURCHASE_PLAN, GET_PURCHASE_PLAN_ALL, UPDATE_PURCHASE_PLAN, CREATE_PURCHASE_PLAN,
	GET_ORDER, GET_ORDER_ALL, UPDATE_ORDER, GET_CAR_FUEL_ORDER, GET_CAR_FUEL_ORDER_ALL, UPDATE_CAR_FUEL_ORDER,
	CREATE_CAR_FUEL_ORDER, GET_HOUSE_FUEL_ORDER, GET_HOUSE_FUEL_ORDER_ALL, UPDATE_HOUSE_FUEL_ORDER,CREATE_HOUSE_FUEL_ORDER,
	GET_CAR_CUSTOMER, GET_CAR_CUSTOMER_ALL,  UPDATE_CAR_CUSTOMER, CREATE_CAR_CUSTOMER, GET_HOUSE_OWNER, GET_HOUSE_OWNER_ALL, 
	UPDATE_HOUSE_OWNER, CREATE_HOUSE_OWNER ,GET_FUEL_TYPE, GET_FUEL_TYPE_ALL, UPDATE_FUEL_TYPE, GET_DISCOUNT_TABLE, 
	GET_DISCOUNT_TABLE_ALL, UPDATE_DISCOUNT_TABLE, GET_FUEL_STOCK, GET_FUEL_STOCK_ALL, UPDATE_FUEL_STOCK, GET_FUEL_REPLENISH, 
	GET_FUEL_REPLENISH_ALL, UPDATE_FUEL_REPLENISH, CREATE_FUEL_REPLENISH, GET_HOUSE_FUEL_INFO, GET_HOUSE_FUEL_INFO_ALL, 
	UPDATE_HOUSE_FUEL_INFO, CREATE_HOUSE_FUEL_INFO, GET_RECEIPT, GET_RECEIPT_ALL, UPDATE_RECEIPT, CREATE_RECEIPT, GET_CAR, 
	GET_CAR_ALL, UPDATE_CAR, CREATE_CAR, GET_SUBSCRIPTION, GET_SUBSCRIPTION_ALL, UPDATE_SUBSCRIPTION, GET_MONTHLY_SIMPLE, 
	GET_MONTHLY_SIMPLE_ALL, UPDATE_MONTHLY_SIMPLE, CREATE_MONTHLY_SIMPLE, GET_MONTHLY_MULTIPLE, GET_MONTHLY_MULTIPLE_ALL, 
	UPDATE_MONTHLY_MULTIPLE, CREATE_MONTHLY_MULTIPLE, GET_MONTHLY_FULL, GET_MONTHLY_FULL_ALL, UPDATE_MONTHLY_FULL, 
	CREATE_MONTHLY_FULL, GET_CASH, GET_CASH_ALL, UPDATE_CASH, CREATE_CASH, GET_CREDIT_CARD, GET_CREDIT_CARD_ALL, UPDATE_CREDIT_CARD, 
	CREATE_CREDIT_CARD, GET_MONTHLY, GET_MONTHLY_ALL, UPDATE_MONTHLY, CREATE_MONTHLY, GET_WORKER, GET_WORKER_ALL, UPDATE_WORKER, 
	GET_LOCATION, GET_LOCATION_ALL, UPDATE_LOCATION, GET_STATION, GET_STATION_ALL, UPDATE_STATION, GET_PERIODIC_DISCOUNT_TEMPLATE,
	GET_PERIODIC_DISCOUNT_TEMPLATE_ALL, UPDATE_PERIODIC_DISCOUNT_TEMPLATE,CREATE_PERIODIC_DISCOUNT_TEMPLATE,
	GET_PERIODIC_DISCOUNT, GET_PERIODIC_DISCOUNT_ALL, UPDATE_PERIODIC_DISCOUNT,CREATE_PERIODIC_DISCOUNT, GET_REPORT,
	GET_REPORT_ALL, UPDATE_REPORT, GET_PERIODIC_CUSTOMER_REPORT, GET_PERIODIC_CUSTOMER_REPORT_ALL, UPDATE_PERIODIC_CUSTOMER_REPORT,
	CREATE_PERIODIC_CUSTOMER_REPORT, GET_DATA_PER_CUSTOMER, GET_DATA_PER_CUSTOMER_ALL, UPDATE_DATA_PER_CUSTOMER,
	CREATE_DATA_PER_CUSTOMER, GET_STOCK_REPORT, GET_STOCK_REPORT_ALL, UPDATE_STOCK_REPORT, CREATE_STOCK_REPORT,
	GET_AMOUNT_DATA_PER_FUEL, GET_AMOUNT_DATA_PER_FUEL_ALL, UPDATE_AMOUNT_DATA_PER_FUEL, CREATE_AMOUNT_DATA_PER_FUEL,
	GET_PURCHASES_REPORT, GET_PURCHASES_REPORT_ALL, UPDATE_PURCHASES_REPORT, CREATE_PURCHASES_REPORT , GET_DISCOUNT_FEEDBACK_REPORT,
	GET_DISCOUNT_FEEDBACK_REPORT_ALL, UPDATE_DISCOUNT_FEEDBACK_REPORT, CREATE_DISCOUNT_FEEDBACK_REPORT, GET_INCOME_REPORT,
	GET_INCOME_REPORT_ALL, UPDATE_INCOME_REPORT, CREATE_INCOME_REPORT , GET_GENERATED_SCORE_REPORT, GET_GENERATED_SCORE_REPORT_ALL,
	UPDATE_GENERATED_SCORE_REPORT, CREATE_GENERATED_SCORE_REPORT, GET_DATA_PER_CUSTOMER_TYPE, GET_DATA_PER_CUSTOMER_TYPE_ALL,
	UPDATE_DATA_PER_CUSTOMER_TYPE,CREATE_DATA_PER_CUSTOMER_TYPE, GET_SCORE_PER_FUEL_TYPE, GET_SCORE_PER_FUEL_TYPE_ALL, 
	UPDATE_SCORE_PER_FUEL_TYPE, CREATE_SCORE_PER_FUEL_TYPE,CREATE_USER,CREATE_USER_TYPE,CREATE_ORDER,CREATE_CUSTOMER,CREATE_FUEL_TYPE
	,CREATE_LOGIN;
}
