package GUI;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import entities.DiscountFeedbackReport;
import entities.GeneratedScoreReport;
import entities.IncomeReport;
import entities.PeriodicCustomerReport;
import entities.PurchasesReport;
import entities.Report;
import entities.StockReport;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JTextArea;
import controllers.ReportControl;
import java.awt.SystemColor;
/**
 * Basic Report Screen, in that screen the user will input all the basic report data, ID and Date is Self Generated by the System.
 * when pressing "next" the user will be moved to the report screen he pressed on in the menu.
 *
 */
public class ReportGUI extends JFrame {
	
	private static final long serialVersionUID = 1L;
	private JTextField textField_1;
	private JTextField textField_3;
	protected JFrame prevScreen;
	protected JFrame report;
	private JTextArea textArea = new JTextArea();
	protected int type;
	private Calendar currCal;
	private String currDate;
	private JFrame thisScreen;
	public ReportGUI(int t, JFrame prev) {
		getContentPane().setBackground(SystemColor.activeCaption);
		currCal=Calendar.getInstance();
		currDate=String.format("%4d-%2d-%2d", currCal.get(Calendar.YEAR),currCal.get(Calendar.MONTH)+1,currCal.get(Calendar.DAY_OF_MONTH));
		currDate = currDate.replace(' ','0');
		type = t;
		this.thisScreen=this;
		setTitle("Report");
		this.report=prevScreen;
		this.prevScreen = prev;
		getContentPane().setLayout(null);
		
		JLabel lblReportTitle = new JLabel("Title:");
		lblReportTitle.setBounds(93, 11, 52, 28);
		getContentPane().add(lblReportTitle);
		
		textField_1 = new JTextField();
		textField_1.setColumns(10);
		textField_1.setBounds(139, 15, 104, 20);
		getContentPane().add(textField_1);
		
		JLabel lblReportDescription = new JLabel("Description:");
		lblReportDescription.setBounds(10, 113, 78, 22);
		getContentPane().add(lblReportDescription);
		
		JLabel lblReportdate = new JLabel("Date:");
		lblReportdate.setBounds(93, 65, 36, 14);
		getContentPane().add(lblReportdate);
		
		textField_3 = new JTextField();
		textField_3.setEnabled(false);
		textField_3.setColumns(10);
		textField_3.setBounds(139, 62, 104, 20);
		getContentPane().add(textField_3);
		textField_3.setText(currDate);
		
		JButton btnCancel = new JButton("Return");
		btnCancel.setBackground(SystemColor.inactiveCaptionBorder);
		btnCancel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				getPrevScreen().setVisible(true);
				dispose();
				
			}
		});
		btnCancel.setBounds(10, 171, 89, 23);
		getContentPane().add(btnCancel);
		
		
		textArea.setLineWrap(true);
		textArea.setBounds(91, 93, 206, 63);
		getContentPane().add(textArea);
		JButton btnNext = new JButton("Next");
		btnNext.setBackground(SystemColor.inactiveCaptionBorder);
		btnNext.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			
				
				List<Report> sl = new LinkedList<Report>();
			    sl = ReportControl.getAllReports();
			    int maxRID=-1;
			    for(Report s : sl)
			     if(s.getReportID()>maxRID)
			      maxRID=s.getReportID();
				
				switch (type)
				{
				case 1:
					DiscountFeedbackReport dfr=new DiscountFeedbackReport();
					dfr.setReportID(maxRID+1);
					dfr.setReportTitle(textField_1.getText());
					dfr.setReportDate(currDate);
					dfr.setReportDesc(textArea.getText());
					new DiscountFeedbackGenerationScreen(prevScreen,dfr);
					getThisScreen().setVisible(false);
					break;
				case 2:
					GeneratedScoreReport gcr= new GeneratedScoreReport();
					gcr.setReportID(maxRID+1);
					gcr.setReportTitle(textField_1.getText());
					gcr.setReportDate(currDate);
					gcr.setReportDesc(textArea.getText());
					new GeneratedScoreReportTimingScreen(prevScreen,gcr);
					getThisScreen().setVisible(false);
					break;
				case 3:
					IncomeReport ic=new IncomeReport();
					ic.setReportID(maxRID+1);
					ic.setReportTitle(textField_1.getText());
					ic.setReportDate(currDate);
					ic.setReportDesc(textArea.getText());
					new IncomeReportTimingScreen(prevScreen,ic);
					getThisScreen().setVisible(false);
					break;
				
				case 4:
					PeriodicCustomerReport pcr=new PeriodicCustomerReport();
					pcr.setReportID(maxRID+1);
					pcr.setReportTitle(textField_1.getText());
					pcr.setReportDate(currDate);
					pcr.setReportDesc(textArea.getText());
					new PeriodicCustomerReportTimingScreen(prevScreen,pcr);
					getThisScreen().setVisible(false);
					break;
					
				case 5:
					PurchasesReport pr=new PurchasesReport();
					pr.setReportID(maxRID+1);
					pr.setReportTitle(textField_1.getText());
					pr.setReportDate(currDate);
					pr.setReportDesc(textArea.getText());
					new PurchasesReportTimingScreen(prevScreen,pr);
					getThisScreen().setVisible(false);
					break;
				case 6:
					StockReport sr= new StockReport();
					sr.setReportID(maxRID+1);
					sr.setReportTitle(textField_1.getText());
					sr.setReportDate(currDate);
					sr.setReportDesc(textArea.getText());
					new StockReportGenerationScreen(prevScreen,sr);
					getThisScreen().setVisible(false);
					break;
				}
					
				setVisible(false);
				dispose ();
			}
		});
		btnNext.setBounds(288, 171, 89, 23);
		getContentPane().add(btnNext);
		
		
		this.setSize(403, 244);
		this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		this.setVisible(true);
		
	}
	
	public JFrame getPrevScreen() {
		return prevScreen;
	}
	public JFrame getThisScreen() {
		return thisScreen;
	}
}
